services:
  importfeed:
    build: importfeed
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mariadb:10.11
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: apa
      MYSQL_DATABASE: knzoon
      MYSQL_USER: knzoonApp
      MYSQL_PASSWORD: appApa
    volumes:
      - db-volume:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-volume: