services:
  readfeed:
    build: readfeed
    environment:
      DB_USER_PASSWORD: ${DB_USER_PASSWD}
      FEED_READ_SAFE_MODE: ${FEED_READ_SAFE_MODE}
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  exportfeed:
    build: exportfeed
    environment:
      PORT: 8000
      DB_USER_PASSWORD: ${DB_USER_PASSWD}
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    image: mariadb:11.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_DATABASE: knzoon
      MYSQL_USER: knzoonApp
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
    volumes:
      - db-volume:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  db-volume: